pipeline {
    agent any
    parameters {
        choice(name: 'AMBIENTE_ALVO', choices: ['des', 'prd'], description: 'Selecione o ambiente de deploy')
    }
    stages {
        stage('Executar Pipeline Completa') {
            steps {
                script {
                    echo "Iniciando a pipeline para o ambiente: ${params.AMBIENTE_ALVO}"
                    dir('getting-started') {
                        sh "./pipeline.sh ${params.AMBIENTE_ALVO}"
                    }
                }
            }
        }
    }
}