pipeline {
    agent any
    stages {
        stage('Executar Pipeline Completa') {
            steps {
                script {
                    def ambiente = ''
                    if (env.BRANCH_NAME == 'main') {
                        ambiente = 'prd'
                    } else if (env.BRANCH_NAME == 'dev') {
                        ambiente = 'des'
                    } else {
                        echo "Branch ${env.BRANCH_NAME} não tem pipeline configurada. Ignorando."
                        return
                    }

                    echo "Iniciando a pipeline para o ambiente: ${ambiente}"
                    dir('getting-started') {
                        sh "./pipeline.sh ${ambiente}"
                    }
                }
            }
        }
    }
}